[package]
name = "AlbumOrganizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
image = "0.24.6"
minifb = "0.24"
polars = "0.28.0"
egui = "0.21.0"
eframe = "0.21.3"