name: Pytest

# This test is slow due to dependency installation of DLIB.
# TODO: add post to show test status on homepage
on: 
  workflow_dispatch: # For now we trigger tests manually only
#[push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.USER }}/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest